service:
  opendota:
    baseUrl: https://api.opendota.com/api
    match_endpoint: /matches
    players_endpoint: /players
    pro_players_endpoint: /proPlayers

cassandra:
  contactpoints: 10.0.0.32,10.0.0.38,10.0.0.49
  port: 9042
  keyspace: big_dota_ks
  table: replay_3

app.name : bigdota
out.path: /tmp/dota
---
spring:
  profiles: dev
env: dev

---
spring:
  profiles: prod
env: prod