service:
  opendota:
    baseUrl: https://api.opendota.com/api
    match_endpoint: /matches
    players_endpoint: /players
    pro_players_endpoint: /proPlayers

cassandra:
  contactpoints: 192.168.1.2,192.168.1.5,192.168.1.10
#  contactpoints: 10.0.0.50
  port: 9042
  keyspace: big_dota_ks
#  table: replay_3
  table: replay

jdbc:
  url: "192.168.1.10"
  port: "5432"
  userName: "postgres"
  password: "password"
  database: "big_dota"
  tableName: "best_combination"
  driver: "org.postgresql.Driver"
app.name : bigdota
out.path: /tmp/dota
---
spring:
  profiles: dev
env: dev

---
spring:
  profiles: prod
env: prod